[window]

opacity = 0.5

# decorations = "Full"
# decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "inconsolata"
bold.family = "inconsolata"
italic.family = "inconsolata"
bold_italic.family = "inconsolata"

size = 17.0

# Tip: for inspiration, look for values in the source code files of your favorite VS Code themes, and use the color picker in
# Google to test colors before setting a value, or simply using an editor such as VS Code where colors are displayed in a 
# small box when a HEX is detected by the editor.
