-- Generated by nwg-displays on 2026-05-30 at 01:47:19. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@59.95",
    position = "0x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@164.85",
    position = "1440x0",
    scale = 1.0
})
